
//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by UyghurEdit.rc
//

#define IDD_ABOUTBOX                    100
#define IDD_SETFONT                     101
#define IDD_MUQEDDIME                   102
#define IDD_IZDESH                      103
#define IDM_VIEW_TOOLBAR                104
#define IDM_VIEW_STATUSBAR              105
#define STBAR_QURSTON                   106
#define STBAR_UNICODE                   107
#define STBAR_QISTURUSH                 108
#define STBAR_APTOR                     109
#define STBAR_TIME                      110
#define UKEY_CTRLA                      112
#define UKEY_CTRLC                      113
#define UKEY_CTRLV                      114
#define UKEY_CTRLX                      115
#define UKEY_CTRLHOME                   116
#define UKEY_CTRLEND                    117
#define IDR_UPOPUP                      118
#define IDD_TALLASHDLG_DIALOG           121
#define IDD_KUNUPKA                     123
#define IDD_ELIPBE                      124

#define IDR_TOOLBAR                     127
#define IDR_UYGHUREDITICO_S             128
#define IDR_UYGHUREDITICO               129
#define IDR_TESTTEXT                    130

#define IDR_RES_UEY                     131
#define IDR_RES_ULY                     132
#define IDR_RES_USY                     133
#define IDR_RES_JPN                     134
#define IDR_RES_ENG                     135
#define IDR_RES_CHN                     136
#define IDR_RES_GER                     137

#define IDC_MYSTATIC1                   138
#define IDC_MYSTATIC2                   139
#define IDC_MYSTATIC3                   140
#define IDC_MYSTATIC4                   141
#define IDD_UFILEOPEN                   142

#define HOJJET_YENGI                    501
#define HOJJET_ECHISH                   502
#define HOJJET_SAQLASH                  503
#define HOJJET_BSAQLASH                 504
#define HOJJET_HTML                     505
#define HOJJET_BESISH                   506
#define HOJJET_BOQUSH                   507
#define HOJJET_QEKINISH                 508
#define HOJJET_BOQUSH_BOGHDA            509
#define HOJJET_BOQUSH_ISO8859_1         510
#define HOJJET_BOQUSH_UTF_16LE          511
#define HOJJET_BOQUSH_UTF_8             512
#define HOJJET_BOQUSH_UTF_16BE          513
#define HOJJET_BOQUSH_UTF_7             514
#define HOJJET_BOQUSH_1250              515
#define HOJJET_BOQUSH_GB2312            516
#define HOJJET_BOQUSH_932               517
#define HOJJET_BOQUSH_950               518
#define HOJJET_BOQUSH_1251              519
#define HOJJET_BOQUSH_1253              520
#define HOJJET_BOQUSH_1254              521
#define HOJJET_BOQUSH_1255              522
#define HOJJET_BOQUSH_1256              523
#define HOJJET_BOQUSH_1257              524
#define HOJJET_BOQUSH_JEUC              525
#define HOJJET_BOQUSH_WEIFANGDOS        526
#define HOJJET_BOQUSH_WEIFANGWIN        527
#define TEHRIR_HEM_TAL                  530
#define TEHRIR_KOCHURUSH                531
#define TEHRIR_CHAPLASH                 532
#define TEHRIR_KESISH                   533
#define TEHRIR_OCHURUSH                 534
#define TEHRIR_HOJJETBESHI              535
#define TEHRIR_HOJJETAHIRI              536
#define TEHRIR_TALNIUKY                 537
#define TEHRIR_TALNIKONA                538
#define TEHRIR_TALNICHONG               539
#define TEHRIR_TALNIKICHIK              540
#define TEHRIR_IZDESH                   541
#define TEHRIR_IZDESH_DAWAMLASHTURUSH   542
#define TEHRIR_BCHAPLASH_UYGHURSOFT     543
#define TEHRIR_BCHAPLASH_UIGHUR_NOTEPAD 544
#define TEHRIR_BCHAPLASH_ILIKYURT       545
#define TEHRIR_BCHAPLASH_DULDUL         546
#define TEHRIR_KOCHURUSH_ALL            547
#define TEHRIR_BCHAPLASH                549
#define TEHRIR_TALNISLAWIYAN            550
#define TEHRIR_TALSLAWIYANUEY           551
#define TEHRIR_TALNITURK                552
#define TEHRIR_TALTURKUEY               553
#define BASHQA_KUNUPKA                  560
#define BASHQA_KUNUPKA_KONA             561
#define BASHQA_KUNUPKA_UKY              562
#define BASHQA_TIZISHABZAS              563
#define BASHQA_TIZISHHEMME              564
#define BASHQA_XETNUSXISI               565
#define BASHQA_SOLDINONG                566
#define BASHQA_UKYGEAYLAN               567
#define BASHQA_KONAGHAAYLAN             568
#define BASHQA_KONAGHAAYLAN_TXT         569
#define BASHQA_KONAGHAAYLAN_PRG         570
#define BASHQA_KONAGHAAYLAN_INF         571
#define BASHQA_IMLA                     572
#define YARDEM_KUNUPKA                  580
#define YARDEM_ELIPPE                   581
#define YARDEM_HEQQIDE                  582
#define RESIM_ELIPBE                    700
#define RESIM_KUNUPKA                   701
#define RESIM_KORSETKUCH                702
#define TEHRIR_YENIWELISH               705
#define TEHRIR_QILISH                   706
#define UEDIT_BITKONA                   708
#define UEDIT_BITUKY                    709

#define TEHRIR_BCHAPLASH_BASHQILAR      710
//#define BASHQA_ALAHIDE_UYGHUR           715
//#define BASHQA_ALAHIDE_LATIN            716
//#define BASHQA_UYGHUR_ALAHIDE           717
#define KOCHUR_ALA2UYGHUR               718
#define BASHQA_UBUNTU                   719

#define BASHQA_UEY                      720
#define BASHQA_ULY                      721
#define BASHQA_USY                      722
#define BASHQA_OTY                      723
#define BASHQA_UMY                      724

#define BASHQA_UYGHUR2LATIN             725
#define BASHQA_UYGHUR2SLAWIYAN          726
#define BASHQA_UYGHUR2MEWHUM            727
#define BASHQA_LATIN2UYGHUR             728
#define BASHQA_LATIN2SLAWIYAN           729
#define BASHQA_LATIN2MEWHUM             730
#define BASHQA_SLAWIYAN2UYGHUR          731
#define BASHQA_SLAWIYAN2LATIN           732
#define BASHQA_SLAWIYAN2MEWHUM          733
#define BASHQA_MEWHUM2UYGHUR            734
#define BASHQA_MEWHUM2LATIN             735
#define BASHQA_MEWHUM2SLAWIYAN          736

#define IDC_COMBO1                      1001
#define IDC_COMBO2                      1002
#define IDC_COMBO3                      1003
#define IDC_COMBO4                      1004
#define IDC_CHECK1                      1005
#define IDC_CHECK2                      1006
#define IDC_KORNUSH                     1009
#define LABFONT_UYGHUR                  1010
#define LABFONT_SYSTEM                  1011
#define LABFONT_SIZE                    1012
#define LABFONT_BOSHLUQ                 1013
#define LABFONT_KORNUSH                 1014
#define SETFONT_TAMAM                   1015
#define SETFONT_CANCEL                  1016
#define TAL_BTN_HE                      1041
#define TAL_BTN_HEMMNI                  1042
#define TAL_BTN_YAQ                     1043
#define TAL_BTN_TOHTA                   1044
#define USERMSG_SOZGEPARCHILASH         1045
#define USERLG_UEY                      1046
#define USERLG_ULY                      1047
#define USERLG_USY                      1048
#define USERLG_JAPANESE                 1049
#define USERLG_ENGLISH                  1050
#define USERLG_CHINESE                  1051
#define USERLG_GERMAN                   1052
#define USERMSG_SOZGEPARCHILASH_YOQ     1500
#define USERMSG_ABZASQA_PARCHILASH      1501
#define USERLG_UYGHUR                   1502
#define USERMSG_BARSOZNI_TAP		    1503

#define UFILE_DLGCODELBL                2000
#define UFILE_DLGCODE                   2001
#define UFILEOPEN_CODELBL               2002
#define UFILEOPEN_CODE                  2003
#define UFILEOPEN_BELGISI               2004
#define UFILEOPEN_ASASIRAYON            2005
#define UUKY_HERIP_EE_CHONG             2006
#define UUKY_HERIP_OO_CHONG             2007
#define UUKY_HERIP_UU_CHONG             2008
#define UUKY_HERIP_EE_KICHIK            2009
#define UUKY_HERIP_OO_KICHIK            2010
#define UUKY_HERIP_UU_KICHIK            2011
#define BASHQA_KUNUPKA_OZGERT           2012
#define BASHQA_KUNUPKA_SYSTEM           2013
#define BASHQA_KUNUPKA_ALAHIDE          2014
#define USERMSG_APTOMATIC_TOGHRILA      2015
#define BIRIKME_PIRSENT_S               2016
#define BIRIKME_QAYTURUSH               2017
#define BIRIKME_PUTUNSAN_D              2018

#define HOJJET_IZ                       2030
#define SHOW_BUFFER_MESSAGE             3000
#define SHOW_ATHOR                      3001


#define MB_YESNOSTOP                    5000
#define MB_YESNOALLSTOP                 5001

#define UM_WINDOWCLOSED                 WM_APP+1
#define UM_WINDOWSTATUS                 WM_APP+2
#define UM_WINDOWTOOLBAR                WM_APP+3
#define UM_NOTIFYPARENT                 WM_APP+4
#define UM_BUYRUQ                       WM_APP+5
#define UM_IMLA                         WM_APP+6

